# Generated by Django 6.0.5 on 2026-06-02 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_symbol', models.CharField(max_length=20, unique=True, verbose_name='Ticker Symbol')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Instrumen')),
                ('instrument_type', models.CharField(choices=[('Saham', 'Saham'), ('Crypto', 'Crypto'), ('Reksadana', 'Reksadana'), ('Lainnya', 'Lainnya')], default='Saham', max_length=20, verbose_name='Tipe Instrumen')),
                ('current_price', models.DecimalField(decimal_places=4, default=0.0, max_digits=20, verbose_name='Harga Terkini')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Terakhir Diperbarui')),
            ],
            options={
                'verbose_name': 'Instrumen Investasi',
                'verbose_name_plural': 'Instrumen Investasi',
            },
        ),
        migrations.CreateModel(
            name='UserAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Jumlah')),
                ('average_buy_price', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Harga Beli Rata-rata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tanggal Diperbarui')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assets', to='portfolio.investmentinstrument', verbose_name='Instrumen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Aset Pengguna',
                'verbose_name_plural': 'Aset Pengguna',
                'unique_together': {('user', 'instrument')},
            },
        ),
    ]
