# Generated by Django 6.0.5 on 2026-06-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentinstrument',
            name='provider',
            field=models.CharField(choices=[('YAHOO', 'Yahoo Finance'), ('COINGECKO', 'CoinGecko'), ('SCRAPER', 'Web Scraper'), ('MANUAL', 'Manual')], default='YAHOO', max_length=20, verbose_name='Data Provider'),
        ),
        migrations.AlterField(
            model_name='investmentinstrument',
            name='instrument_type',
            field=models.CharField(choices=[('Saham', 'Saham'), ('Crypto', 'Crypto'), ('Emas', 'Emas'), ('Reksadana', 'Reksadana'), ('Obligasi', 'Obligasi')], default='Saham', max_length=20, verbose_name='Tipe Instrumen'),
        ),
    ]
